/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class id_seigan_dojo_Run */

#ifndef _Included_id_seigan_dojo_Run
#define _Included_id_seigan_dojo_Run
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     id_seigan_dojo_Run
 * Method:    controls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_id_seigan_dojo_Run_controls
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
